name: ci

on: [push, pull_request]

jobs:
  tests:
    name: Python ${{ matrix.python-version }} tests
    runs-on: ubuntu-latest
    
    strategy:
      max-parallel: 5
      matrix:
        python-version: [2.7, 3.7, 3.8, 3.9]

    steps:
    - name: Checkout qiBullet Github repository
      uses: actions/checkout@v2
      with:
        lfs: true
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: 'x64'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy --upgrade
        pip install pybullet
        pip install codecov
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Install qiBullet
      run: python setup.py develop --agree-license
    - name: Tests
      run: |
        cd tests
        coverage run test_launcher.py
    - name: Coverage
      run: |
        cd tests
        bash <(curl -s https://codecov.io/bash)

  package:
    name: Deploy package
    needs: tests
    if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout qiBullet Github repository
      uses: actions/checkout@v2
      with:
          lfs: true
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Publish qiBullet to Test PyPI 📦
      uses: pypa/gh-action-pypi-publish@v1.4.2
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
    - name: Publish qiBullet to PyPI 📦
      uses: pypa/gh-action-pypi-publish@v1.4.2
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}

  documentation:
    needs: package
    name: Deploy pages
    if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout qiBullet Github repository
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Build the Doxygen documentation
      uses: mattnotmitt/doxygen-action@v1.1.0
      with:
        working-directory: docs
        doxyfile-path: ./Doxyfile
    - name: Deploy the documentation to Github pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/api/
        enable_jekyll: false
        allow_empty_commit: false
        force_orphan: true
        publish_branch: gh-pages
